---
# Source: kminion/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kminion
  namespace: "unhelm-namespace-placeholder"
  labels:
    helm.sh/chart: kminion-0.11.3
    app.kubernetes.io/name: kminion
    app.kubernetes.io/instance: kminion
    app.kubernetes.io/version: "v2.2.5"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    {}
