---
# Source: kminion/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kminion
  namespace: "unhelm-namespace-placeholder"
  labels:
    helm.sh/chart: kminion-0.11.3
    app.kubernetes.io/name: kminion
    app.kubernetes.io/instance: kminion
    app.kubernetes.io/version: "v2.2.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kminion
      app.kubernetes.io/instance: kminion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kminion
        app.kubernetes.io/instance: kminion
    spec:
      serviceAccountName: kminion
      securityContext:
        fsGroup: 99
        runAsUser: 99
      volumes:
        - name: config
          configMap:
            name: kminion
      initContainers:
      containers:
        - name: kminion
          securityContext:
            {}
          image: "redpandadata/kminion:v2.2.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            - name: CONFIG_FILEPATH
              value: /etc/kminion/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/kminion
          resources:
            {}
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
