---
# Source: grafana/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: grafana
    chart: grafana-3.4.2
    release: release-name
    heritage: Tiller
  name: release-name-grafana-clusterrole
rules: []
