---
# Source: grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: logs-grafana
  namespace: default
  labels:
    app: grafana
    chart: grafana-3.4.2
    heritage: Tiller
    release: logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logs-grafana
subjects:
- kind: ServiceAccount
  name: logs-grafana
  namespace: default