---
# Source: grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: logs-grafana
  namespace: default
  labels:
    app: grafana
    chart: grafana-3.4.2
    release: logs
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YTRBR3dVUmNISTdESjhJNFJlcDRnOGgyUmRGYURHQmdXWEZXTDZiRA=="
  ldap-toml: ""
