---
# Source: grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: release-name-grafana
  labels:
    app: grafana
    chart: grafana-3.3.6
    release: release-name
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "bWNTNW5IelN2VHk1ZVYwUGJPeDRBc1FFajc4R1pzMElSZ0hZcEp0Vg=="
  ldap-toml: ""
