---
# Source: loki/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-loki
  labels:
    app: loki
    chart: loki-0.10.0
    heritage: Tiller
    release: release-name
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [release-name-loki]

