---
# Source: loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: logs-loki
  labels:
    app: loki
    chart: loki-0.10.0
    release: logs
    heritage: Tiller
  annotations:
    {}
    
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: logs
