resources:
- ./templates/service_account.yaml
- ./templates/configmap.yaml
- ./templates/clusterrole.yaml
- ./templates/clusterrole_metrics.yaml
- ./templates/clusterrole_proxy.yaml
- ./templates/clusterrole_binding.yaml
- ./templates/clusterrole_proxy_binding.yaml
- ./templates/role.yaml
- ./templates/role_binding.yaml
- ./templates/service_metrics.yaml
- ./templates/service_webhook.yaml
- ./templates/deployment.yaml
- ./templates/certificate.yaml
- ./templates/issuer.yaml
- ./templates/mutating_webhook.yaml
- ./templates/validating_webhook.yaml

