---
# Source: openreplay/charts/http/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: http-0.1.0
    app.kubernetes.io/name: http
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
