---
# Source: mariadb-galera/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb-mariadb-galera-headless
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.10.1
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: galera
      port: 4567
      targetPort: galera
    - name: ist
      port: 4568
      targetPort: ist
    - name: sst
      port: 4444
      targetPort: sst
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: mariadb
