---
# Source: mariadb-galera/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: ystack-mariadb-galera-metrics
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.10.1
    app.kubernetes.io/instance: ystack
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9104
      targetPort: metrics
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: ystack
