---
# Source: mariadb-galera/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.10.1
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "VTYyUGx4NDY0TQ=="
  mariadb-password: "OGtaSFVTUlZyWA=="
  mariadb-galera-mariabackup-password: "SmVvQThhd3oxdw=="
