---
# Source: mariadb-galera/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.10.1
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "QmkwOHpCcUNwZg=="
  mariadb-password: "N3paUVYxOVo5ZA=="
  mariadb-galera-mariabackup-password: "R0lubWNqWGlyTA=="
