---
# Source: mariadb-galera/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: ystack-mariadb-galera
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.10.1
    app.kubernetes.io/instance: ystack
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      nodePort: null
  selector:
    app.kubernetes.io/name: mariadb-galera
    app.kubernetes.io/instance: ystack
