---
# Source: redpanda/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-default-cert
  namespace: "unhelm-namespace-placeholder"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-4.0.47
spec:
  dnsNames:
  - redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc.cluster.local
  - redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc
  - redpanda-cluster.redpanda.unhelm-namespace-placeholder
  - "*.redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc.cluster.local"
  - "*.redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc"
  - "*.redpanda-cluster.redpanda.unhelm-namespace-placeholder"
  - redpanda.unhelm-namespace-placeholder.svc.cluster.local
  - redpanda.unhelm-namespace-placeholder.svc
  - redpanda.unhelm-namespace-placeholder
  - "*.redpanda.unhelm-namespace-placeholder.svc.cluster.local"
  - "*.redpanda.unhelm-namespace-placeholder.svc"
  - "*.redpanda.unhelm-namespace-placeholder"
  duration: 43800h
  isCA: false
  secretName: redpanda-default-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: redpanda-default-root-issuer
    kind: Issuer
    group: cert-manager.io
---
# Source: redpanda/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-external-cert
  namespace: "unhelm-namespace-placeholder"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-4.0.47
spec:
  dnsNames:
  - redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc.cluster.local
  - redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc
  - redpanda-cluster.redpanda.unhelm-namespace-placeholder
  - "*.redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc.cluster.local"
  - "*.redpanda-cluster.redpanda.unhelm-namespace-placeholder.svc"
  - "*.redpanda-cluster.redpanda.unhelm-namespace-placeholder"
  - redpanda.unhelm-namespace-placeholder.svc.cluster.local
  - redpanda.unhelm-namespace-placeholder.svc
  - redpanda.unhelm-namespace-placeholder
  - "*.redpanda.unhelm-namespace-placeholder.svc.cluster.local"
  - "*.redpanda.unhelm-namespace-placeholder.svc"
  - "*.redpanda.unhelm-namespace-placeholder"
  duration: 43800h
  isCA: false
  secretName: redpanda-external-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: redpanda-external-root-issuer
    kind: Issuer
    group: cert-manager.io
