---
# Source: redpanda/templates/post-upgrade.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: redpanda-post-upgrade
  namespace: "unhelm-namespace-placeholder"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-4.0.47
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "redpanda"
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/instance: "redpanda"
        app.kubernetes.io/component: redpanda-post-upgrade
    spec:
      restartPolicy: Never
      securityContext: 
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: default
      containers:
      - name: redpanda-post-upgrade
        image: docker.redpanda.com/redpandadata/redpanda:v23.1.12
        command: ["/bin/sh", "-c"]
        args:
          - |
            rpk cluster config import -f /tmp/base-config/bootstrap.yaml --api-urls redpanda-0.redpanda.unhelm-namespace-placeholder.svc.cluster.local.:9644,redpanda-1.redpanda.unhelm-namespace-placeholder.svc.cluster.local.:9644,redpanda-2.redpanda.unhelm-namespace-placeholder.svc.cluster.local.:9644 --admin-api-tls-enabled --admin-api-tls-truststore /etc/tls/certs/default/ca.crt
            rpk cluster config set storage_min_free_bytes 1073741824 --api-urls redpanda-0.redpanda.unhelm-namespace-placeholder.svc.cluster.local.:9644,redpanda-1.redpanda.unhelm-namespace-placeholder.svc.cluster.local.:9644,redpanda-2.redpanda.unhelm-namespace-placeholder.svc.cluster.local.:9644 --admin-api-tls-enabled --admin-api-tls-truststore /etc/tls/certs/default/ca.crt
        securityContext: 
          runAsUser: 101
          runAsGroup: 101
        volumeMounts:
          - name: redpanda
            mountPath: /tmp/base-config
          - name: config
            mountPath: /etc/redpanda
          - name: redpanda-default-cert
            mountPath: /etc/tls/certs/default
          - name: redpanda-external-cert
            mountPath: /etc/tls/certs/external
      volumes:
        - name: redpanda
          configMap:
            name: redpanda
        - name: config
          emptyDir: {}
        - name: redpanda-default-cert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
            secretName: redpanda-default-cert
        - name: redpanda-external-cert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
            secretName: redpanda-external-cert
