---
# Source: mimir/templates/store-gateway/store-gateway-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-store-gateway
  labels:
    helm.sh/chart: mimir-4.0.0
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
  namespace: "mimir"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      #app.kubernetes.io/instance: unhelm
      app.kubernetes.io/component: store-gateway
  maxUnavailable: 1
