---
# Source: redpanda-operator/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-serving-cert
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.11.2
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.11.2"
    app.kubernetes.io/managed-by: Helm
spec:
  dnsNames:
    - redpanda-operator-webhook-service.redpanda-system.svc
    - redpanda-operator-webhook-service.redpanda-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: unhelm-redpanda-operator-selfsigned-issuer
  secretName: webhook-server-cert
