---
# Source: redpanda-operator/templates/clusterrole_proxy_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unhelm-redpanda-operator-proxy-role
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.7.6
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.7.6"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unhelm-redpanda-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: unhelm-redpanda-operator
  namespace: redpanda-system
