---
# Source: redpanda-operator/templates/clusterrole_metrics.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RELEASE-NAME-redpanda-operator-metrics-reader
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.6.5
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v21.6.5"
    app.kubernetes.io/managed-by: Helm
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
