---
# Source: redpanda-operator/templates/clusterrole_metrics.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unhelm-redpanda-operator-metrics-reader
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.9.2
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.9.2"
    app.kubernetes.io/managed-by: Helm
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
