---
# Source: redpanda-operator/templates/clusterrole_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME-redpanda-operator
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.6.5
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v21.6.5"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-redpanda-operator
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-redpanda-operator
  namespace: unhelm-namespace-placeholder
