---
# Source: redpanda-operator/templates/issuer.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: unhelm-redpanda-operator-selfsigned-issuer
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.11.10
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.11.10"
    app.kubernetes.io/managed-by: Helm
spec:
  selfSigned: {}
