---
# Source: redpanda-operator/templates/issuer.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: RELEASE-NAME-redpanda-operator-selfsigned-issuer
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.6.5
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v21.6.5"
    app.kubernetes.io/managed-by: Helm
spec:
  selfSigned: {}
