---
# Source: redpanda-operator/templates/mutating_webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: unhelm-namespace-placeholder/redpanda-serving-cert
  name: unhelm-redpanda-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      service:
        name: redpanda-operator-webhook-service
        namespace: unhelm-namespace-placeholder
        path: /mutate-redpanda-vectorized-io-v1alpha1-cluster
    failurePolicy: Fail
    name: mcluster.kb.io
    rules:
    - apiGroups:
      - redpanda.vectorized.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - clusters
    sideEffects: None
