---
# Source: redpanda-operator/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unhelm-redpanda-operator-election-rolebinding
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.6.5
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.6.5"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: unhelm-redpanda-operator
  namespace: redpanda-system
roleRef:
  kind: Role
  name: unhelm-redpanda-operator-election-role
  apiGroup: rbac.authorization.k8s.io
