---
# Source: redpanda-operator/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unhelm-redpanda-operator-election-role
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.11.2
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.11.2"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
