---
# Source: redpanda-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unhelm-redpanda-operator
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v21.9.2
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v21.9.2"
    app.kubernetes.io/managed-by: Helm
