---
# Source: redpanda-operator/templates/service_webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: redpanda-operator-webhook-service
  labels:
    app.kubernetes.io/name: redpanda-operator
    helm.sh/chart: redpanda-operator-v22.1.3
    app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "v22.1.3"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: unhelm
