# yaml-language-server: $schema=https://github.com/cockroachdb/helm-charts/raw/master/cockroachdb/values.schema.json
# unhelm-template-repo: https://charts.cockroachdb.com/

tls:
  serviceAccount:
    create: false
  certs:
    selfSigner:
      enabled: false
      caProvided: false
    certManager: true
