version: '2'

services:

  logs:
    image: yolean/ystack-runner:6be9ec5eb04edf6cc1f670a4d556ca408916e564@sha256:dc2b930963699ff0ca45876911c25ac38631754b779db71bb1806e2de5b3b044
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./logs:/workspace/logs:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add grafana https://grafana.github.io/helm-charts
      mkdir -p /tmp/unhelm/logs/{grafana,loki,fluent-bit}
      echo 'resources:' > /tmp/unhelm/logs/grafana/kustomization.yaml
      echo 'resources:' > /tmp/unhelm/logs/loki/kustomization.yaml
      echo 'resources:' > /tmp/unhelm/logs/fluent-bit/kustomization.yaml
      helm template logs grafana/grafana -f logs/grafana.yaml --namespace monitoring --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/grafana/|- ./|'  | tee -a /tmp/unhelm/logs/grafana/kustomization.yaml
      helm template logs grafana/loki                         --namespace monitoring --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/loki/|- ./|'     | tee -a /tmp/unhelm/logs/loki/kustomization.yaml
      helm template logs grafana/fluent-bit                   --namespace monitoring --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/fluent-bit/|- ./|' | tee -a /tmp/unhelm/logs/fluent-bit/kustomization.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/logs/* ./logs/"

  mysql:
    image: yolean/ystack-runner:6be9ec5eb04edf6cc1f670a4d556ca408916e564@sha256:dc2b930963699ff0ca45876911c25ac38631754b779db71bb1806e2de5b3b044
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./mysql:/workspace/mysql:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add bitnami https://charts.bitnami.com/bitnami
      helm search repo bitnami
      mkdir -p /tmp/unhelm/mysql/mariadb-galera
      echo 'resources:' > /tmp/unhelm/mysql/mariadb-galera/kustomization.yaml
      helm template ystack bitnami/mariadb-galera -f mysql/mariadb-galera.yaml --namespace unhelm-namespace-placeholder --output-dir /tmp/unhelm/mysql | sed 's|wrote /tmp/unhelm/mysql/mariadb-galera/|- ./|'  | tee -a /tmp/unhelm/mysql/mariadb-galera/kustomization.yaml
      # Opinions, https://github.com/Yolean/kubernetes-mysql-cluster/pull/35
      sed -i.org 's/\butf8/utf8mb4/' /tmp/unhelm/mysql/mariadb-galera/templates/configmap.yaml
      sed -i 's/plugin_load_add=auth_pam/#plugin_load_add=auth_pam/' /tmp/unhelm/mysql/mariadb-galera/templates/configmap.yaml
      # Your Kustomize base must override:
      grep -rn unhelm-namespace-placeholder /tmp/unhelm/mysql
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/mysql/* ./mysql/"

  redpanda:
    image: yolean/ystack-runner:6be9ec5eb04edf6cc1f670a4d556ca408916e564@sha256:dc2b930963699ff0ca45876911c25ac38631754b779db71bb1806e2de5b3b044
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./redpanda:/workspace/redpanda:ro
    # https://vectorized.io/docs/quick-start-kubernetes
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add redpanda https://charts.vectorized.io/
      helm search repo redpanda
      export VERSION=$$(curl -s https://api.github.com/repos/vectorizedio/redpanda/releases/latest | jq -r .tag_name)
      mkdir -p /tmp/unhelm/redpanda/redpanda-operator-crd /tmp/unhelm/redpanda/redpanda-operator /tmp/unhelm/redpanda/redpanda
      kubectl kustomize https://github.com/vectorizedio/redpanda/src/go/k8s/config/crd?ref=$${VERSION} > /tmp/unhelm/redpanda/redpanda-operator-crd/redpanda-operator-crd.yaml
      echo 'resources:' > /tmp/unhelm/redpanda/redpanda-operator/kustomization.yaml
      helm template unhelm redpanda/redpanda-operator -f /workspace/redpanda/redpanda-operator.yaml --namespace unhelm-namespace-placeholder --output-dir /tmp/unhelm/redpanda | sed 's|wrote /tmp/unhelm/redpanda/redpanda-operator/|- ./|'  | tee -a /tmp/unhelm/redpanda/redpanda-operator/kustomization.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/redpanda/* ./redpanda/"
