version: '2'

services:

  helm-loki:
    build: ./helm3
    command:
    - /bin/bash
    - -cex
    - |
      helm version
      helm repo add grafana https://grafana.github.io/helm-charts
      mkdir -p logs/loki/
      echo 'resources:' > logs/loki/kustomization.yaml
      mkdir -p logs/promtail/
      echo 'resources:' > logs/promtail/kustomization.yaml
      helm template logs grafana/loki --namespace monitoring --output-dir ./logs | sed 's|wrote ./logs/loki/|- ./|' | tee -a logs/loki/kustomization.yaml
      helm template logs grafana/promtail --namespace monitoring --output-dir ./logs | sed 's|wrote ./logs/promtail/|- ./|' | tee -a logs/promtail/kustomization.yaml
      echo "Done"
      echo "There are no mounted volumes. Use docker cp to extract the results."
      sleep 300
