version: '2'

services:

  logs:
    build: ./helm3
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./logs:/workspace/logs:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add grafana https://grafana.github.io/helm-charts
      mkdir -p /tmp/unhelm/logs/{grafana,loki,fluent-bit}
      echo 'resources:' > /tmp/unhelm/logs/grafana/kustomization.yaml
      echo 'resources:' > /tmp/unhelm/logs/loki/kustomization.yaml
      echo 'resources:' > /tmp/unhelm/logs/fluent-bit/kustomization.yaml
      helm template logs grafana/grafana -f logs/grafana.yaml --namespace monitoring --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/grafana/|- ./|'  | tee -a /tmp/unhelm/logs/grafana/kustomization.yaml
      helm template logs grafana/loki                         --namespace monitoring --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/loki/|- ./|'     | tee -a /tmp/unhelm/logs/loki/kustomization.yaml
      helm template logs grafana/fluent-bit                   --namespace monitoring --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/fluent-bit/|- ./|' | tee -a /tmp/unhelm/logs/fluent-bit/kustomization.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/logs/* ./logs/"

  mysql:
    build: ./helm3
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./mysql:/workspace/mysql:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add bitnami https://charts.bitnami.com/bitnami
      helm search repo bitnami
      mkdir -p /tmp/unhelm/mysql/mariadb-galera
      echo 'resources:' > /tmp/unhelm/mysql/mariadb-galera/kustomization.yaml
      helm template ystack bitnami/mariadb-galera -f mysql/mariadb-galera.yaml --namespace unhelm-namespace-placeholder --output-dir /tmp/unhelm/mysql | sed 's|wrote /tmp/unhelm/mysql/mariadb-galera/|- ./|'  | tee -a /tmp/unhelm/mysql/mariadb-galera/kustomization.yaml
      # Opinions, https://github.com/Yolean/kubernetes-mysql-cluster/pull/35
      sed -i.org 's/\butf8/utf8mb4/' /tmp/unhelm/mysql/mariadb-galera/templates/configmap.yaml
      # Your Kustomize base must override:
      grep -rn unhelm-namespace-placeholder /tmp/unhelm/mysql
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/mysql/* ./mysql/"
