version: '2'

services:

  # There are no mounted volumes. We've used docker cp to extract the results.

  helm-charts:
    build: ./helm-docker
    command:
    - /bin/sh
    - -cex
    - |
      mkdir -p /workspace
      cd /workspace
      [ ! -d ./charts ] && git clone --depth 1 -b master https://github.com/helm/charts ./charts
      helm template ./charts/stable/grafana/ --output-dir .
      helm template ./charts/stable/minio/ --output-dir . \
        --set "mode=distributed"
      echo "Done"

  helm-loki:
    build: ./helm-docker
    command:
    - /bin/sh
    - -cex
    - |
      mkdir -p /workspace
      cd /workspace
      [ ! -d ./loki-repo ] && git clone --depth 1 -b master https://github.com/grafana/loki ./loki-repo
      helm template ./loki-repo/production/helm/loki --name logs --output-dir .
      helm template ./loki-repo/production/helm/promtail --name logs --output-dir .
      echo "Done"

  # The origin of many dashboards in prometheus-operator's kube-prometheus
  kubernetes-mixin:
    build: ./jsonnet-docker
    command:
    - /bin/sh
    - -cex
    - |
      mkdir -p /workspace
      git clone --branch v0.1.0 https://github.com/kubernetes-monitoring/kubernetes-mixin /kubernetes-mixin
      cd /kubernetes-mixin
      cp LICENSE /workspace/
      jb install
      make prometheus_alerts.yaml
      cp prometheus_alerts.yaml /workspace/
      make prometheus_rules.yaml
      cp prometheus_rules.yaml /workspace/
      make dashboards_out
      cp -r dashboards_out /workspace/dashboards
      echo "Done"
