version: '2'

services:

  mimir:
    image: docker.io/yolean/ystack-runner:cd9cb05b51adf3a9b545c622c7424421ebb4945e@sha256:d48744967206aade113797f728d4dd67b0dcebb805e2665146605bcc55539728
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./mimir:/workspace/mimir:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add grafana https://grafana.github.io/helm-charts
      mkdir -p /tmp/unhelm/mimir/mimir-distributed
      echo 'resources:' > /tmp/unhelm/mimir/mimir-distributed/kustomization.yaml
      cat <<EOF > /tmp/unhelm/mimir/mimir-distributed/kustomization.yaml
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      secretGenerator:
      - name: mimir-config
        files:
        - mimir.yaml
      resources:
      EOF
      helm template unhelm grafana/mimir-distributed -f /workspace/mimir/mimir-distributed.values.yaml    --namespace mimir --output-dir /tmp/unhelm/mimir | sed 's|wrote /tmp/unhelm/mimir/mimir-distributed/|- ./|'     | tee -a /tmp/unhelm/mimir/mimir-distributed/kustomization.yaml
      yq e '.data."mimir.yaml"' /tmp/unhelm/mimir/mimir-distributed/templates/mimir-config.yaml > /tmp/unhelm/mimir/mimir-distributed/mimir.yaml
      sed -i 's|- ./templates/mimir-config.yaml|#- ./templates/mimir-config.yaml|' /tmp/unhelm/mimir/mimir-distributed/kustomization.yaml
      find /tmp/unhelm/mimir/ -type f -exec sed -i 's|unhelm-||g' '{}' \;
      find /tmp/unhelm/mimir/ -type f -exec sed -i 's| app.kubernetes.io/instance: unhelm| #app.kubernetes.io/instance: unhelm|g' '{}' \;
      find /tmp/unhelm/mimir/ -type f -exec sed -i 's|-distributed||g' '{}' \;
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/mimir/* ./mimir/"

  logs:
    image: docker.io/yolean/ystack-runner:cd9cb05b51adf3a9b545c622c7424421ebb4945e@sha256:d48744967206aade113797f728d4dd67b0dcebb805e2665146605bcc55539728
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./logs:/workspace/logs:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add grafana https://grafana.github.io/helm-charts
      mkdir -p /tmp/unhelm/logs/{grafana,loki,loki-distributed}
      echo 'resources:' > /tmp/unhelm/logs/grafana/kustomization.yaml
      echo 'resources:' > /tmp/unhelm/logs/loki/kustomization.yaml
      cat <<EOF > /tmp/unhelm/logs/loki-distributed/kustomization.yaml
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      configMapGenerator:
      - name: loki
        files:
        - config.yaml
      patchesJson6902:
      - target:
          version: v1
          kind: Service
          name: loki-query-frontend
        patch: |-
          - op: remove
            path: /spec/clusterIP
      resources:
      EOF
      helm template unhelm grafana/grafana -f /workspace/logs/grafana.values.yaml --namespace logs --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/grafana/|- ./|'  | tee -a /tmp/unhelm/logs/grafana/kustomization.yaml
      helm template unhelm grafana/loki    -f /workspace/logs/loki.values.yaml    --namespace logs --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/loki/|- ./|'     | tee -a /tmp/unhelm/logs/loki/kustomization.yaml
      helm template unhelm grafana/loki-distributed -f /workspace/logs/loki-distributed.values.yaml    --namespace logs --output-dir /tmp/unhelm/logs | sed 's|wrote /tmp/unhelm/logs/loki-distributed/|- ./|'     | tee -a /tmp/unhelm/logs/loki-distributed/kustomization.yaml
      yq e '.data."config.yaml"' /tmp/unhelm/logs/loki-distributed/templates/configmap.yaml > /tmp/unhelm/logs/loki-distributed/config.yaml
      sed -i 's|- ./templates/configmap.yaml|#- ./templates/configmap.yaml|' /tmp/unhelm/logs/loki-distributed/kustomization.yaml
      find /tmp/unhelm/logs/ -type f -exec sed -i 's|unhelm-||g' '{}' \;
      find /tmp/unhelm/logs/ -type f -exec sed -i 's| app.kubernetes.io/instance: unhelm| #app.kubernetes.io/instance: unhelm|g' '{}' \;
      find /tmp/unhelm/logs/ -type f -exec sed -i 's|-distributed||g' '{}' \;
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/logs/* ./logs/"

  mysql:
    image: docker.io/yolean/ystack-runner:cd9cb05b51adf3a9b545c622c7424421ebb4945e@sha256:d48744967206aade113797f728d4dd67b0dcebb805e2665146605bcc55539728
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./mysql:/workspace/mysql:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add bitnami https://charts.bitnami.com/bitnami
      helm search repo bitnami
      mkdir -p /tmp/unhelm/mysql/mariadb-galera
      echo 'resources:' > /tmp/unhelm/mysql/mariadb-galera/kustomization.yaml
      helm template ystack bitnami/mariadb-galera -f mysql/mariadb-galera.yaml --namespace unhelm-namespace-placeholder --output-dir /tmp/unhelm/mysql | sed 's|wrote /tmp/unhelm/mysql/mariadb-galera/|- ./|'  | tee -a /tmp/unhelm/mysql/mariadb-galera/kustomization.yaml
      # Opinions, https://github.com/Yolean/kubernetes-mysql-cluster/pull/35
      sed -i.org 's/\butf8/utf8mb4/' /tmp/unhelm/mysql/mariadb-galera/templates/configmap.yaml
      sed -i 's/plugin_load_add=auth_pam/#plugin_load_add=auth_pam/' /tmp/unhelm/mysql/mariadb-galera/templates/configmap.yaml
      # Your Kustomize base must override:
      grep -rn unhelm-namespace-placeholder /tmp/unhelm/mysql
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/mysql/* ./mysql/"

  redpanda:
    image: docker.io/yolean/ystack-runner:cd9cb05b51adf3a9b545c622c7424421ebb4945e@sha256:d48744967206aade113797f728d4dd67b0dcebb805e2665146605bcc55539728
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./redpanda:/workspace/redpanda:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      mkdir -p /tmp/unhelm/redpanda/redpanda
      echo 'resources:' > /tmp/unhelm/redpanda/redpanda/kustomization.yaml
      helm template --repo https://charts.redpanda.com redpanda redpanda -f /workspace/redpanda/without-tls.values.yaml --namespace unhelm-namespace-placeholder --output-dir /tmp/unhelm/redpanda | sed 's|wrote /tmp/unhelm/redpanda/redpanda/|- ./|' | sort | uniq | tee -a /tmp/unhelm/redpanda/redpanda/kustomization.yaml
      mv /tmp/unhelm/redpanda/redpanda /tmp/unhelm/redpanda/without-tls
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/redpanda/* ./redpanda/"

  vault:
    image: docker.io/yolean/ystack-runner:cd9cb05b51adf3a9b545c622c7424421ebb4945e@sha256:d48744967206aade113797f728d4dd67b0dcebb805e2665146605bcc55539728
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./vault:/workspace/vault:ro
    # https://learn.hashicorp.com/tutorials/vault/kubernetes-google-cloud-gke
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add hashicorp https://helm.releases.hashicorp.com
      helm repo update
      helm search repo vault --versions
      mkdir -p /tmp/unhelm/vault/raft
      echo 'resources:' > /tmp/unhelm/vault/raft/kustomization.yaml
      helm template vault hashicorp/vault -n unhelm-namespace-placeholder -f /workspace/vault/vault-raft.values.yaml --output-dir /tmp/unhelm/vault/raft | sed 's|wrote /tmp/unhelm/vault/raft/vault/|- ./vault/|' | grep -v /tests/ | tee -a /tmp/unhelm/vault/raft/kustomization.yaml
      sed -i 's/  namespace: unhelm-namespace-placeholder/  #namespace: unhelm-namespace-placeholder/' /tmp/unhelm/vault/raft/vault/templates/*.yaml /tmp/unhelm/vault/raft/vault/templates/tests/*.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/vault/* ./vault/"

  fluent-bit:
    image: docker.io/yolean/ystack-runner:cd9cb05b51adf3a9b545c622c7424421ebb4945e@sha256:d48744967206aade113797f728d4dd67b0dcebb805e2665146605bcc55539728
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./fluent-bit:/workspace/fluent-bit:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      helm repo add fluent https://fluent.github.io/helm-charts
      helm repo update
      helm search repo fluent-bit --versions
      mkdir -p /tmp/unhelm/fluent-bit
      echo 'resources:' > /tmp/unhelm/fluent-bit/kustomization.yaml
      helm template fluent-bit fluent/fluent-bit -f /workspace/fluent-bit/fluent-bit.values.yaml -n unhelm-namespace-placeholder --output-dir /tmp/unhelm | sed 's|wrote /tmp/unhelm/fluent-bit/|- ./|' | tee -a /tmp/unhelm/fluent-bit/kustomization.yaml
      sed -i 's/  namespace: unhelm-namespace-placeholder/  #namespace: unhelm-namespace-placeholder/' /tmp/unhelm/fluent-bit/templates/*.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/fluent-bit/* ./fluent-bit/"

  thanos:
    build: ./jsonnet-docker
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./thanos:/workspace/thanos:ro
    command:
    - /bin/bash
    - -cx
    - |
      mkdir -p /tmp/unhelm/thanos
      cd /tmp/unhelm/thanos
      jb init
      jb install github.com/thanos-io/kube-thanos/jsonnet/kube-thanos@main
      cp /workspace/thanos/example.jsonnet .
      git --no-pager diff
      . build.sh
      git --no-pager diff
      cat <<EOF >kustomization.yaml
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      resources:
      EOF
      find manifests -name '*.yaml' | sed 's/^/- /' >>kustomization.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/thanos/* ./thanos/"

  openreplay:
    image: docker.io/yolean/ystack-runner:755de97a9e73114abea98bd8c8247186de560c49
    working_dir: /tmp
    volumes:
    - /tmp/unhelm:/tmp/unhelm:rw
    - ./openreplay:/workspace/openreplay:ro
    command:
    - /bin/bash
    - -cx
    - |
      set -eo pipefail
      helm version
      git clone https://github.com/openreplay/openreplay.git
      cd openreplay/scripts/helmcharts/
      mkdir -p /tmp/unhelm/openreplay/databases /tmp/unhelm/openreplay/openreplay
      echo 'resources:' > /tmp/unhelm/openreplay/databases/kustomization.yaml
      echo 'resources:' > /tmp/unhelm/openreplay/openreplay/kustomization.yaml
      helm template ./databases/ -f ./vars.yaml -n unhelm-namespace-placeholder --output-dir /tmp/unhelm/openreplay | sed 's|wrote /tmp/unhelm/openreplay/databases/|- ./|' | tee -a /tmp/unhelm/openreplay/databases/kustomization.yaml
      helm template ./openreplay/ -f ./vars.yaml -n unhelm-namespace-placeholder --output-dir /tmp/unhelm/openreplay | sed 's|wrote /tmp/unhelm/openreplay/openreplay/|- ./|' | tee -a /tmp/unhelm/openreplay/openreplay/kustomization.yaml
      sed -i 's|- ./charts/ingress|#- ./charts/ingress|' /tmp/unhelm/openreplay/openreplay/kustomization.yaml
      sed -i 's|- \(.*\)/ingress.yaml|#- \1/ingress.yaml|' /tmp/unhelm/openreplay/openreplay/kustomization.yaml
      set +x
      echo "Done. To extract the results:"
      echo "rsync -av --delete /tmp/unhelm/openreplay/* ./openreplay/"
