version: '2'

services:

  # There are no mounted volumes. We've used docker cp to extract the results.

  helm-loki:
    build: ./helm-docker
    command:
    - /bin/sh
    - -cex
    - |
      mkdir -p /workspace
      cd /workspace
      [ ! -d ./loki-repo ] && git clone --depth 1 -b master https://github.com/grafana/loki ./loki-repo
      echo 'resources:' > logs/loki/kustomization.yaml
      helm template ./loki-repo/production/helm/loki --name logs --namespace logs --output-dir ./logs | sed 's|wrote ./logs/loki/|- ./|' | tee -a logs/loki/kustomization.yaml
      helm template ./loki-repo/production/helm/promtail --name logs --namespace logs --output-dir ./logs
      echo "Done"
