---
# Source: openreplay/charts/alerts/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alerts-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: alerts-0.1.0
    app.kubernetes.io/name: alerts
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
