apiVersion: v1
data:
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    redpanda:
        data_directory: /var/lib/redpanda/data
        node_id: 0
        seed_servers:
            - host:
                address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
        rpc_server:
            address: 0.0.0.0
            port: 33145
        kafka_api:
            - address: 0.0.0.0
              port: 9092
              name: kafka
        admin:
            - address: 0.0.0.0
              port: 9644
              name: admin
        advertised_rpc_api:
            address: 0.0.0.0
            port: 33145
        developer_mode: true
        auto_create_topics_enabled: false
        log_segment_size: 536870912
    rpk:
        enable_usage_stats: false
        tune_network: false
        tune_disk_scheduler: false
        tune_disk_nomerges: false
        tune_disk_write_cache: false
        tune_disk_irq: false
        tune_fstrim: false
        tune_cpu: false
        tune_aio_events: false
        tune_clocksource: false
        tune_swappiness: false
        tune_transparent_hugepages: false
        enable_memory_locking: false
        tune_coredump: false
        coredump_dir: /var/lib/redpanda/coredump
        tune_ballast_file: false
        overprovisioned: false
    pandaproxy:
        pandaproxy_api:
            - address: 0.0.0.0
              port: 8082
              name: proxy
    pandaproxy_client:
        brokers:
            - address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
    schema_registry:
        schema_registry_api:
            - address: 0.0.0.0
              port: 8081
              name: schema-registry
    schema_registry_client:
        brokers:
            - address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
kind: ConfigMap
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzEVs+vozYQ/leQz4GQTTZNuLbXqlIPvfRV1mBPiIWx3bHhbXaV/70yhDwSeFrtU6Ull/DNN9/8MB77GwOn/kLyyhpWsG7DVkxCAFZ8Y4TSgZGQXaDRrGDCmpOq+ElpLJI1BrEeGesH6osZX4sXkyRJEgW5VIQiWLoUyboDWmtVvvlHxsA1ViJXskjy4d0jSu6ROiR/k4tPmpytDxMgPiAlofdFMuqmeXbP7I7hF2icxsx3IhO69QEp01aAzh7VnKVQJNvtZvd5MJATt0wmce8x86z/vVlm/jWcauDg1EMd7wuMEsf8+GmKGmiwGNQGGGSjzI+K7ne7uWivNIp2SEF5lDwW/pj2D1QtsUNtHRJvrMQiCdTiLUIbLBeEEJAH65TwHA2UGmWRnED7G03binusGjSBe/UVi+Tzdn/4JT9uPr0YcvUtrcGVtx4q5D5A8A8qoTXIDYZXS/XcIJWvuRdnlK1GesdubINU4YJub34lFZALEGd8h6Ho37nl5AOpZo4L185BUJZjh2apOKGtqL1tSSzE96/gnDL9mj3bAoHxDig2+NxW6OC5yFtvG2wsXXiMo0y1kIEllG3jHiwjGAfA0tYf7ROdErQGH26TZqJlOyRHtlNxXE0+k17Jkf1yuX0Mb8AH9tshPyzst15tGooLrdCMM6gkWz+PqP9zHk1HQfxQG+CElfKBxpqf0I8VvpkXPuimo+4s/M/rA7uuWK2MZAX7tT+bfgfHVqzBAOMZpqFE7eM/cC6r2xLJYECfKbsWtnHWoAmsuJ91bLVAVMYHMAK/x2vAQIUyLS8TZhpnHwRLiy6xxd+TdUAhtacp7bpiT55pCR7ZAHsHD8mOrWUrZl8N0p94QkIj0LPi76cbwH1duv60Vl9Rxhy6DWh3hng9KOP+/yPq/IYaQ+8Wh/oqXhACWa2RRmRcnWE52SxrtmKtiox9nu9Ph90mlfv9Id0JgPS4O2zTw1HIfCv3+f64Ydd/rtf/AgAA//9QSwcI2A3h4esCAACxCAAAUEsBAhQAFAAIAAgAAAAAANgN4eHrAgAAsQgAAAgAAAAAAAAAAAAAAAAAAAAAAG9yaWdpbmFsUEsFBgAAAAABAAEANgAAACEDAAAAAA==
  creationTimestamp: "2022-05-14T05:28:47Z"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: redpanda-operator
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: redpanda
  name: redpanda-base
  namespace: redpanda-example
  ownerReferences:
  - apiVersion: redpanda.vectorized.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: redpanda
    uid: 6006f841-d668-4caa-9483-89cd03d60691
  resourceVersion: "2444"
  uid: 15a7d22c-ba66-4eed-b0b7-8a8692112e68
