---
# Source: openreplay/charts/assist/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assist-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: assist-0.1.0
    app.kubernetes.io/name: assist
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: assist
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: assist
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: assist-openreplay
      securityContext:
        {}
      containers:
        - name: assist
          securityContext:
            {}
          image: "public.ecr.aws/p1t3u8a3/assist:v1.8.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: ASSIST_KEY
              value: SetARandomStringHere
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: S3_HOST
              value: 'https://:443'
            - name: S3_KEY
              value: changeMeMinioAccessKey
            - name: S3_SECRET
              value: changeMeMinioPassword
            - name: CLEAR_SOCKET_TIME
              value: '720'
            - name: REDIS_URL
              value: 'redis://redis-master.db.svc.cluster.local:6379'
            - name: debug
              value: '0'
            - name: redis
              value: 'false'
            - name: uws
              value: 'false'
          ports:
            - name: socketio
              containerPort: 9001
              protocol: TCP
          resources:
            {}
