---
# Source: openreplay/charts/heuristics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heuristics-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: heuristics-0.1.0
    app.kubernetes.io/name: heuristics
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
