---
# Source: openreplay/charts/db/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: db-0.1.0
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: db-openreplay
      securityContext:
        {}
      containers:
        - name: db
          securityContext:
            {}
          image: "public.ecr.aws/p1t3u8a3/db:v1.8.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: LICENSE_KEY
              value: ''
            - name: REDIS_STRING
              value: 'redis-master.db.svc.cluster.local:6379'
            - name: KAFKA_SERVERS
              value: 'kafka.db.svc.cluster.local:9092'
            - name: KAFKA_USE_SSL
              value: 'false'
            - name: POSTGRES_STRING
              value: 'postgres://postgres:changeMePassword@postgresql.db.svc.cluster.local:5432/postgres'
            - name: QUICKWIT_ENABLED
              value: 'false'
            - name: CLICKHOUSE_STRING
              value: 'tcp://clickhouse-openreplay-clickhouse.db.svc.cluster.local:9000/default'
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
          resources:
            {}
