---
# Source: openreplay/charts/db/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: db-0.1.0
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
