---
# Source: databases/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: unhelm-namespace-placeholder
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-3.7.14
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  access-key: "Y2hhbmdlTWVNaW5pb0FjY2Vzc0tleQ=="
  secret-key: "Y2hhbmdlTWVNaW5pb1Bhc3N3b3Jk"
