apiVersion: v1
data:
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    redpanda:
        data_directory: /var/lib/redpanda/data
        node_id: 0
        seed_servers:
            - host:
                address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
            - host:
                address: redpanda-1.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
            - host:
                address: redpanda-2.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
        rpc_server:
            address: 0.0.0.0
            port: 33145
        kafka_api:
            - address: 0.0.0.0
              port: 9092
              name: kafka
        admin:
            - address: 0.0.0.0
              port: 9644
              name: admin
        advertised_rpc_api:
            address: 0.0.0.0
            port: 33145
        developer_mode: false
        auto_create_topics_enabled: false
        default_topic_replications: 3
        id_allocator_replication: 3
        log_segment_size: 536870912
        transaction_coordinator_replication: 3
    rpk:
        enable_usage_stats: false
        tune_network: false
        tune_disk_scheduler: false
        tune_disk_nomerges: false
        tune_disk_write_cache: false
        tune_disk_irq: false
        tune_fstrim: false
        tune_cpu: false
        tune_aio_events: false
        tune_clocksource: false
        tune_swappiness: false
        tune_transparent_hugepages: false
        enable_memory_locking: false
        tune_coredump: false
        coredump_dir: /var/lib/redpanda/coredump
        tune_ballast_file: false
        overprovisioned: false
    pandaproxy:
        pandaproxy_api:
            - address: 0.0.0.0
              port: 8082
              name: proxy
    pandaproxy_client:
        brokers:
            - address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
            - address: redpanda-1.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
            - address: redpanda-2.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
    schema_registry: {}
kind: ConfigMap
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzEVkFv6zYM/iuGznHiNE1e4+t2HQbssMs6CLREO4JlSaNk9+UV+e+D7Dh1EhdvLQosvdTkx++jSInSKwOn/kTyyhqWs27NFkxCAJa/MkLpwEhYHqHRLGfCmlJVvFQa82SFQaxGxOoK+mzGz/zZJEmSREIuFaEIlo55suqAVloVb/ERMWCNlciVzJNs+PaIknukDsmf6eIvTQ7Wh4kh/kBKQu/zZORNs+Uls4sNv0PjNC59J5ZCtz4gLbUVoJfXbM5SyJPNZv24/bDu+n/SffhKXXLiXPmJ7kUzW/Z/b567+BrKGjg4ddW39wlGin22f5haDTSYD2yDGWSjzEdJd4+P96Q900jaIQXlUfK48Ou0P7BqiR1q65B4YyXmSQna41miDZYLQgjIg3VKeI4GCo3yCiaxhFaHAcIJnVYCgrLG58lmgCjJQccmBktTxAWgbcU9Vg2awL36gXmy3eyevmX79bm0gcB4EDGIC2tJKjNLRq4+12FIlbceKuQ+QPBXWYfWIDcYXizV9w6pfM29OKBsNdI7fmMbpApneHv3C6mAXIA44DsIRf/ce0ofSDX3duHaeyMoy7FDM7c4oa2ovW1JzOj7F3BOmX6T3Pr6Wjug2IxDW6GD20Wea9tgY+nIo44y1UwGllC2jbvyjMY4Yedm6+if8BSgNfhwHuUTLtshObKdivfBZFv2TI7s9+N5M7wZPnHAn7KnmQPes02luNAKzTj0CrL17R3wlQN/bvbMKXx+tP9Xhc8P8alCPGwNcMJK+RBv3dfTs2GnBauVkSxnv/S3+W/g2II1GGC89TUUqH38D5xb1m2BZDCgXyq7ErZx1qAJLL+8DthiBqiMD2AE/gzXgIEKZVocJ8g0Ts84jGZD4mb5Ga0DCqktp7DTgt1EpgV4ZIPZO7hKdqw3WzD7YpD+wBIJjUDP8r9u3kyXZnX9+0b9QBlz6Nag3QHig6qIB/r3yPMragx9WKAWF/FJFchqjTRaxu4MPWZ3WbMFa1VE7MtsK/DbPn3Y7WX6WG5lWhTlLs0K2DztduUm2wp2+vt0+jcAAP//UEsHCANVBUIZAwAA4wkAAFBLAQIUABQACAAIAAAAAAADVQVCGQMAAOMJAAAIAAAAAAAAAAAAAAAAAAAAAABvcmlnaW5hbFBLBQYAAAAAAQABADYAAABPAwAAAAA=
  creationTimestamp: "2022-05-14T05:28:40Z"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: redpanda-operator
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: redpanda
  name: redpanda-base
  namespace: redpanda-example
  ownerReferences:
  - apiVersion: redpanda.vectorized.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: redpanda
    uid: 9f05ce79-269d-4f5d-bbf6-0ba3866f305c
  resourceVersion: "2333"
  uid: 946fa84e-d210-43c4-ae7b-4efcb1e603e1
