apiVersion: v1
kind: Service
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWy8kzFv2zAQhf/LzZSrOLZqaWvTJUtqpEWXIsOJPCWEKB5Bnty4gf57Qdtx3NSAt27C6X2Px/ekF8Bgf1BMlj00sLkCBb31Bhr4RnFjNYGCgQQNCkLzAg5bcik/YQizfmwpehJKM8sfNA+BPXmBBiKZgN4gqDNC65Og13RJN6DHRzJFuz1RFhwoonA8i3gcLtoGjFJwdyqbFPxL5kkK+NeeBT3jEFyOhX95ivfUUSSvKUHz812ar8xsQ1o42t9k8vGbK3ThCXPUrWPdf80+X8iR7DCJIynQ7CWycxRfJ4dabtyYhCKcW3i0WVF35VLTx7qYV7UpFt3SFG3bVUXZ4vWqqrrrcqlhepgUpEA6V6n3nrdraOCOfb5c4Cj7Kx2OQTNYf3gBTV0tFgpCZGHNDhr4frMGBYLxkWR9lEzqyPfY9fjGl/X8El/W8xM+RH7eHvlVubrEZ8n0oCCMrbPp6Y7lntBsPxkTKaXc1z7XRG5Xz3/6pt+3NimQbaC3Zm/XeZYEZdz9Z47RfEaXvfOO0zT9CQAA//9QSwcIm6hYbpUBAAC1AwAAUEsBAhQAFAAIAAgAAAAAAJuoWG6VAQAAtQMAAAgAAAAAAAAAAAAAAAAAAAAAAG9yaWdpbmFsUEsFBgAAAAABAAEANgAAAMsBAAAAAA==
  creationTimestamp: "2022-05-14T05:28:40Z"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: redpanda-operator
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: redpanda
  name: redpanda
  namespace: redpanda-example
  ownerReferences:
  - apiVersion: redpanda.vectorized.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: redpanda
    uid: 9f05ce79-269d-4f5d-bbf6-0ba3866f305c
  resourceVersion: "2330"
  uid: abffb5e2-e2ff-4ab3-af18-210ce7ba167e
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: admin
    port: 9644
    protocol: TCP
    targetPort: 9644
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: proxy
    port: 8082
    protocol: TCP
    targetPort: 8082
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/name: redpanda
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
