apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzkWO+P4rwR/l+sfmilhB/LHrdE2g8UuC3qS6CE2/bVaYUGZwIWju3aDru8J/73yg5kA8t1e23fV6d2PxlnZjIeP88zk/1KQLFH1IZJQSICSpnmrk0CsmUiJRFJLFjMCp6gJQHJ0UIKFkj0lXBYITduBUo1tsUKtUCLpsFkk8pcSYHCkohoTBWIFEhwxZAJY0FQfM8uBwFrTMPVvmYZSoUarNRXXQTk74ZVoG0os7rZISBvPd2OUXCWZ4gvkCuOJCDyWaCeY4YaBUVDoi8XZT35NHZIrdTsF0zd63dt4GoDrtwrLul26uIMkaP1blYXGBAqhdWSc9SnnePVDHhhLGpyLeGCOYte1vpA8WMvvOn20vA2+5CGq1XWDVsr6Nx1u1mn9YGSw9MhIEYhdVepZDrxpc5R2JnkjLqCz0AD58hJQDQqzigYEnUCYpD78zjPHCzd/PRbYuLy1Ad3DtQ7RjF+UxCLueJg0adaQzEIIS24evu0v3FRVIqMrXNQ4QbMhkQkTXu9mztIaSdrf+x2e6vbj60eAt7R25sM7roORr8pQd4U47thXEMBZBkTzO6PiOgLy/r1Le2grjEdFpqJdUI3mBacifV4LWS1PXpBWpRA/lKGOYZYoM4rAUl+OAhVRXI8flump4BYqSSX6/2f0ZHjPOJGGuujHgLyjGy9sSRqt1qHJ0edvxfs+6r2P16iJxfM6Rswgfqom3p9FpUExFjQrvuEId0g3d5nwA3635DuUFtmMNSKhpCm+v53v59Nh8u4Pxn9oVGx+TLFhtnRBi31s8ElBd6IOp327QcfNcUMCm5DLtchxx3yeyYy6R+ZXN23/SrHXOr9fafbOv75XY1OgfD0tDVxxaAyz8FJ9hfSLIxurphoarV1j1Ds/KmPVZ6PhrN+POwvR/HjeD6NJ6N4QQKyA17gWR3JIaicTuc9GX7S0vMrY8jTOWYlUGrdyPd3/3QG1qnZSRAb5bUcrgRPZv3Bf+sNpQS9ec149u/HNxZsYRpKpuOZi/wUEJbD2oV+VfLmCQaR6wTGXu2cSmpbIrEC5kxqS0p8vHoo6u/gwqjXvb2tbCDNmbhq1erdVFZbyLZwzequdfdqpbR82ZNSRowstOfeV8JZzqxfUVWQiLT9kOawRyJy++BUyMkOmn9qdAjITvIix4ksxPH0uVseq9tES5sXfYREpOyKYcq0T//MYwe6ydmq8mr6hlu5ul/e78lflWB2cC4DF8RIRvPH8WC0/PSXYVwjxPcQvE6ZwTT+NH5YJtPP88FoORzPazGbubDNarJ86zQcJYtx3F+Mp/VMzkpULRp7yHk9RkXw+WywnE3ndXaXAlQzjqfD0X/IbNfRG0Km5UR0RrnR3xajedz/aTmYxvFosBg/jhc/19IpVfY9h2Xy+Y/D6aQ/jt837Q+H81GSLBc/z0Z16z9Nk0VZjG/wtgRa4W8k2t3cNNqNDjlazgrOq0F1nMXSzpwIiyvsDutxyK/FJIO00MzuHaDxxfqpshB986Blodww0A7Kjc/GjfTtVvtXoN8Zhi883Bj7yr0r6Wa1XA9udNY5E35GftBAcYaayTRBKkVqSNS+ab32+0RphHQghbEa2OkwP+gYk8NLssVnErUvB5bTr4sgv0jh5o7nDYrPwoBlJmOw4l6gynEO+2L/DKVQl3da9ZKMrSeg3HEvYbkCT7Rv3FLwlWCu7H7IXOkuzSqbC2ENiHKqYCwK++gTGXBgXj2oW8QXOlzOYoVKwWJiNVhc+1nf7pWzmwr/WerT3L2GWxy/qo6Y/X/678BrocW/+lVFKRozkWk5Ns8R0r9qZnHqTnjZ2OtaY6zUpSa2W60HdtavU7f9iXE0e2Mx9+/zs5DDSvlpf/pZ+3ZvHQ7/CAAA//9QSwcIow/wmYIFAAD5EQAAUEsBAhQAFAAIAAgAAAAAAKMP8JmCBQAA+REAAAgAAAAAAAAAAAAAAAAAAAAAAG9yaWdpbmFsUEsFBgAAAAABAAEANgAAALgFAAAAAA==
  creationTimestamp: "2022-05-14T05:28:40Z"
  generation: 1
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: redpanda-operator
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: redpanda
  name: redpanda
  namespace: redpanda-example
  ownerReferences:
  - apiVersion: redpanda.vectorized.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: redpanda
    uid: 9f05ce79-269d-4f5d-bbf6-0ba3866f305c
  resourceVersion: "2412"
  uid: c3fb44f7-48ee-4a77-a932-5eaff452e967
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: redpanda
      app.kubernetes.io/instance: redpanda
      app.kubernetes.io/name: redpanda
  serviceName: redpanda
  template:
    metadata:
      annotations:
        redpanda.vectorized.io/configmap-hash: dd9928adc3f17669b4709eae8c42fa86
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/name: redpanda
      name: redpanda
      namespace: redpanda-example
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: redpanda
                  app.kubernetes.io/instance: redpanda
                  app.kubernetes.io/name: redpanda
              namespaces:
              - redpanda-example
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: redpanda
                app.kubernetes.io/instance: redpanda
                app.kubernetes.io/name: redpanda
            namespaces:
            - redpanda-example
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - redpanda
        - start
        - --check=false
        - --advertise-rpc-addr=$(POD_NAME).redpanda.redpanda-example.svc.cluster.local.:33145
        - --default-log-level=info
        - --smp=1
        - --memory=3600000000
        - --reserve-memory=0M
        command:
        - /usr/bin/rpk
        env:
        - name: REDPANDA_ENVIRONMENT
          value: kubernetes
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: vectorized/redpanda:latest
        imagePullPolicy: Always
        name: redpanda
        ports:
        - containerPort: 33145
          name: rpc
          protocol: TCP
        - containerPort: 9644
          name: admin
          protocol: TCP
        - containerPort: 9092
          name: kafka
          protocol: TCP
        - containerPort: 8082
          name: proxy
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4G
          requests:
            cpu: "1"
            memory: 4G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/redpanda
          name: config-dir
        - mountPath: /var/lib/redpanda/data
          name: datadir
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: SERVICE_FQDN
          value: redpanda.redpanda-example.svc.cluster.local.
        - name: CONFIG_SOURCE_DIR
          value: /mnt/operator
        - name: CONFIG_DESTINATION
          value: /etc/redpanda/redpanda.yaml
        - name: REDPANDA_RPC_PORT
          value: "33145"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: EXTERNAL_CONNECTIVITY
          value: "false"
        - name: EXTERNAL_CONNECTIVITY_SUBDOMAIN
        - name: EXTERNAL_CONNECTIVITY_ADDRESS_TYPE
        - name: HOST_PORT
        image: vectorized/configurator:v22.1.3
        imagePullPolicy: IfNotPresent
        name: redpanda-configurator
        resources:
          limits:
            cpu: "1"
            memory: 4G
          requests:
            cpu: "1"
            memory: 4G
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/redpanda
          name: config-dir
        - mountPath: /mnt/operator
          name: configmap-dir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
      terminationGracePeriodSeconds: 120
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: redpanda
            app.kubernetes.io/instance: redpanda
            app.kubernetes.io/name: redpanda
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          defaultMode: 420
          name: redpanda-base
        name: configmap-dir
      - emptyDir: {}
        name: config-dir
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/managed-by: redpanda-operator
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/part-of: redpanda
      name: datadir
      namespace: redpanda-example
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: redpanda-6fd79cd767
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: redpanda-6fd79cd767
  updatedReplicas: 3
