---
# Source: cockroachdb/templates/certificate.client.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certmanager-cockroachdb-root-client
  namespace: "unhelm-namespace-placeholder"
  labels:
    helm.sh/chart: cockroachdb-11.0.3
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "certmanager"
    app.kubernetes.io/managed-by: "Helm"
spec:
  duration: 672h
  renewBefore: 48h
  usages:
    - digital signature
    - key encipherment
    - client auth
  keySize: 2048
  keyAlgorithm: rsa
  commonName: root
  organization:
    - Cockroach
  secretName: cockroachdb-root
  issuerRef:
    name: cockroachdb
    kind: Issuer
    group: cert-manager.io
