---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-fluent-bit
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: fluent-bit-0.34.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "2.1.6"
    app.kubernetes.io/managed-by: Helm
