---
# Source: openreplay/charts/ingress-nginx/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.2.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: RELEASE-NAME-ingress-nginx
  namespace: unhelm-namespace-placeholder
automountServiceAccountToken: true
