---
# Source: mimir/templates/query-scheduler/query-scheduler-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mimir-query-scheduler
  namespace: "mimir"
  labels:
    helm.sh/chart: mimir-4.4.1
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/component: query-scheduler
    app.kubernetes.io/version: "2.8.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: 9095
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/component: query-scheduler
