
alertmanager:
  enabled: false

minio:
  enabled: false

nginx:
  enabled: false

overrides_exporter:
  enabled: false

rbac:
  # https://github.com/grafana/helm-charts/issues/1282
  pspEnabled: false
