---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.16.2
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.8.3"
    app.kubernetes.io/managed-by: Helm
