---
# Source: openreplay/charts/sink/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: sink-0.1.0
    app.kubernetes.io/name: sink
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sink
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sink
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: sink-openreplay
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsUser: 0
      containers:
        - name: sink
          securityContext:
            {}
          image: "public.ecr.aws/p1t3u8a3/sink:v1.8.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: LICENSE_KEY
              value: ''
            - name: REDIS_STRING
              value: 'redis-master.db.svc.cluster.local:6379'
            - name: KAFKA_SERVERS
              value: 'kafka.db.svc.cluster.local:9092'
            - name: KAFKA_USE_SSL
              value: 'false'
            # We need to check what is the object store endpoint.
            # There can be 4 options
            # 1. Using minio inside kube clster
            # 2. Using minio managed external cluster, like aws minio offering
            # 3. Using GCP or other object stores compatible with s3 apis
            # 4. Using AWS itself.
            # AWS uses bucketname.endpoint/object while others use endpoint/bucketname/object
            - name: ASSETS_ORIGIN
              # Local minio Installation
              value: 'https:///sessions-assets'
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
          resources:
            {}
          volumeMounts:
          - name: datadir
            mountPath: /mnt/efs
      volumes:
      - name: datadir
        hostPath:
          # Ensure the file directory is created.
          path: /openreplay/storage/nfs
          type: DirectoryOrCreate
