---
# Source: openreplay/charts/sink/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sink-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: sink-0.1.0
    app.kubernetes.io/name: sink
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
