---
# Source: openreplay/charts/chalice/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chalice-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: chalice-0.1.0
    app.kubernetes.io/name: chalice
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: "openreplay" 
  tls:
    - hosts:
        - 
      secretName: openreplay-ssl
  rules:
    - host:  
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: chalice-openreplay
                port:
                  number: 8000
            path: /api/(.*)
