---
# Source: databases/charts/redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: "unhelm-namespace-placeholder"
  labels:
    app: redis
    chart: redis-12.10.1
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    release: RELEASE-NAME
    role: master
