---
# Source: openreplay/charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RELEASE-NAME-ingress-nginx-admission
  namespace: unhelm-namespace-placeholder
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    helm.sh/chart: ingress-nginx-4.2.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.3.0"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-ingress-nginx-admission
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-ingress-nginx-admission
    namespace: "unhelm-namespace-placeholder"
