---
# Source: memcached/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-memcached
  namespace: default
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-3.2.3
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.5.20"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    {}
    
spec:
  clusterIP: None
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: release-name
