---
# Source: openreplay/charts/assets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assets-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: assets-0.1.0
    app.kubernetes.io/name: assets
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
