---
# Source: redpanda/charts/console/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-console
  labels:
    helm.sh/chart: console-0.6.6
    app.kubernetes.io/name: console
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v2.2.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: console
    app.kubernetes.io/instance: default
