apiVersion: v1
data:
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    redpanda:
        data_directory: /var/lib/redpanda/data
        node_id: 0
        seed_servers:
            - host:
                address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
            - host:
                address: redpanda-1.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
            - host:
                address: redpanda-2.redpanda.redpanda-example.svc.cluster.local.
                port: 33145
        rpc_server:
            address: 0.0.0.0
            port: 33145
        kafka_api:
            - address: 0.0.0.0
              port: 9092
              name: kafka
        admin:
            - address: 0.0.0.0
              port: 9644
              name: admin
        advertised_rpc_api:
            address: 0.0.0.0
            port: 33145
        developer_mode: true
        auto_create_topics_enabled: false
        default_topic_replications: 3
        id_allocator_replication: 3
        log_segment_size: 536870912
        transaction_coordinator_replication: 3
    rpk:
        enable_usage_stats: false
        tune_network: false
        tune_disk_scheduler: false
        tune_disk_nomerges: false
        tune_disk_write_cache: false
        tune_disk_irq: false
        tune_fstrim: false
        tune_cpu: false
        tune_aio_events: false
        tune_clocksource: false
        tune_swappiness: false
        tune_transparent_hugepages: false
        enable_memory_locking: false
        tune_coredump: false
        coredump_dir: /var/lib/redpanda/coredump
        tune_ballast_file: false
        overprovisioned: false
    pandaproxy:
        pandaproxy_api:
            - address: 0.0.0.0
              port: 8082
              name: proxy
    pandaproxy_client:
        brokers:
            - address: redpanda-0.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
            - address: redpanda-1.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
            - address: redpanda-2.redpanda.redpanda-example.svc.cluster.local.
              port: 9092
    schema_registry: {}
kind: ConfigMap
metadata:
  annotations:
    banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzEVsFu4zYQ/RWBZ8u21nbW1rW9FgV66KUpiBE5kglRJDuklPUG/veCkuXItoJtggXqXKKZx/eGM+QMXxk49SeSV9awnHUZWzAJAVj+ygilAyNheYJGs5wJa0pV8VJpzJMVBrEaEasb6LMZP/NnkyRJEgm5VIQiWDrlyaoDWmlVvK2PiAFrrESuZJ6sh2+PKLlH6pD8hS7+0uRofZgY4g+kJPQ+T0bedL28Rna14TdonMal78RS6NYHpKW2AvTyls1ZCnmy2WTb3Yd1s/9J98vP1CUnLpmf6F4118v+783zsL6GsgYOTt3U7X2CkeKwPnyZWg00mA9sgxlko8xHSZ+220fSnmkk7ZCC8ih53Pht2B/YtcQOtXVIvLES8yRQixeFNlguCCEgD9Yp4TkaKDTKPClBexwJSmh1GCCc0GklIChrfJ5sBoiSHHSsYbA0RVwB2lbcY9WgCdyr75gnu83T/uv6kF0yGwiMBxEXcWEtSWVmycjVlzQMofLWQ4XcBwj+JurQGuQGw4ul+tEhla+5F0eUrUZ6x29sg1ThDG/vfiEVkAsQR3wHoeifR0/pA6nm0S5c+2gEZTl2aOY2J7QVtbctiRl9/wLOKdOfkXtfn2sHFItxbCt0cL/JS24bbCydeNRRppqJwBLKtnE3ntEYG+xcax39E54CtAYfLp18wmU7JEe2U3EcTI5lz+TIfjtdDsOb4RP3e7/ez9zvnm0qxYVWaMaeV5Ct70fAz+z3c61nTuHznf2/Kny+h08V4mVrgBNWyoc4dF/Pz4adF6xWRrKc/dIP89/AsQVrMMA49DUUqH38D5xb1m2BZDCgXyq7ErZx1qAJLL8+DthiBqiMD2AE/gjXgIEKZVqcJsg0Ns/YjGaXxMPyI1oHFFJbTmHnBbtbmRbgkQ1m7+Am2DHfbMHsi0H6A0skNAI9y/+6ezJdi9X1zxv1HWWMoctAuyPE91QRL/TvkedX1Bj6ZXEqLOKLKpDVGmm0jNUZasweomYL1qqIwGxfZtt1me4OGabb7T5LD193+xQO8JSV+822zHbs/Pf5/G8AAAD//1BLBwgpRSNxHQMAAOIJAABQSwECFAAUAAgACAAAAAAAKUUjcR0DAADiCQAACAAAAAAAAAAAAAAAAAAAAAAAb3JpZ2luYWxQSwUGAAAAAAEAAQA2AAAAUwMAAAAA
  creationTimestamp: "2022-05-14T05:18:23Z"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: redpanda-operator
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: redpanda
  name: redpanda-base
  namespace: redpanda-example
  ownerReferences:
  - apiVersion: redpanda.vectorized.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: redpanda
    uid: e18f140f-591e-4481-9758-a9a61f834f15
  resourceVersion: "1127"
  uid: f90d72eb-fe83-4b24-a0bc-b3a8a862a088
