apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1.2G
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
     - port: 9092
       tls:
         enabled: false
    pandaproxyApi:
     - port: 8082
       tls:
         enabled: false
    adminApi:
    - port: 9644
    developerMode: true
  storage:
    capacity: 1Gi
