server:
  ha:
    enabled: true
    raft:
      enabled: true
  authDelegator:
    enabled: false
  dataStorage:
    size: 1Gi
  auditStorage:
    enabled: true
    size: 1Gi
  postStart:
  - echo
  - "postStart goes here"
injector:
  enabled: false
ui:
  enabled: true
  publishNotReadyAddresses: false
