---
# Source: redpanda/templates/post-upgrade.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minimal-post-upgrade
  namespace: "unhelm-namespace-placeholder"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: minimal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-4.0.47
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "minimal"
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/instance: "minimal"
        app.kubernetes.io/component: redpanda-post-upgrade
    spec:
      restartPolicy: Never
      securityContext: 
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: default
      containers:
      - name: redpanda-post-upgrade
        image: docker.redpanda.com/redpandadata/redpanda:v23.1.13
        command: ["/bin/sh", "-c"]
        args:
          - |
            rpk cluster config import -f /tmp/base-config/bootstrap.yaml --api-urls minimal-0.minimal.unhelm-namespace-placeholder.svc.cluster.local.:9644,minimal-1.minimal.unhelm-namespace-placeholder.svc.cluster.local.:9644,minimal-2.minimal.unhelm-namespace-placeholder.svc.cluster.local.:9644
            rpk cluster config set storage_min_free_bytes 1073741824 --api-urls minimal-0.minimal.unhelm-namespace-placeholder.svc.cluster.local.:9644,minimal-1.minimal.unhelm-namespace-placeholder.svc.cluster.local.:9644,minimal-2.minimal.unhelm-namespace-placeholder.svc.cluster.local.:9644
        securityContext: 
          runAsUser: 101
          runAsGroup: 101
        volumeMounts:
          - name: minimal
            mountPath: /tmp/base-config
          - name: config
            mountPath: /etc/redpanda
      volumes:
        - name: minimal
          configMap:
            name: minimal
        - name: config
          emptyDir: {}
