---
# Source: redpanda/templates/post-install-upgrade-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minimal-configuration
  namespace: "unhelm-namespace-placeholder"
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: minimal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-4.0.47
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-10"
spec:
  template:
    metadata:
      generateName: "minimal-post-"
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/instance: "minimal"
        app.kubernetes.io/component: redpanda-post-install
    spec:
      restartPolicy: Never
      securityContext: 
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: redpanda-post-install
        image: docker.redpanda.com/redpandadata/redpanda:v23.1.13
        command: ["bash","-c"]
        args:
          - |
            set -e
        securityContext: 
          runAsUser: 101
          runAsGroup: 101
        volumeMounts:
          - name: minimal
            mountPath: /tmp/base-config
          - name: config
            mountPath: /etc/redpanda
      volumes:
        - name: minimal
          configMap:
            name: minimal
        - name: config
          emptyDir: {}
      serviceAccountName: default
