---
# Source: openreplay/charts/integrations/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integrations-openreplay
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: integrations-0.1.0
    app.kubernetes.io/name: integrations
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "v1.8.1"
    app.kubernetes.io/managed-by: Helm
