---
# Source: vault/templates/server-discovery-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raft-vault-discovery-rolebinding
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: vault-0.24.1
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: raft
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: raft-vault-discovery-role
subjects:
- kind: ServiceAccount
  name: raft-vault
  namespace: unhelm-namespace-placeholder
