---
# Source: vault/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-vault
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: vault-0.24.1
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: raft
    app.kubernetes.io/managed-by: Helm
