---
# Source: vault/templates/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: raft-vault-ui
  namespace: unhelm-namespace-placeholder
  labels:
    helm.sh/chart: vault-0.24.1
    app.kubernetes.io/name: vault-ui
    app.kubernetes.io/instance: raft
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: raft
    component: server
  publishNotReadyAddresses: false
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  type: ClusterIP
