---
# Source: minio/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: blobs-minio
  labels:
    app: minio
    chart: minio-2.5.6
    release: blobs
    heritage: Tiller
type: Opaque
data:
  accesskey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secretkey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
