---
# Source: minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blobs-minio
  labels:
    app: minio
    chart: minio-2.5.6
    release: blobs
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: blobs
