---
# Source: minio/templates/statefulset.yaml


apiVersion: v1
kind: Service
metadata:
  name: blobs-minio-svc
  labels:
    app: minio
    chart: "minio-2.5.6"
    release: "blobs"
    heritage: "Tiller"
spec:
  clusterIP: None
  ports:
    - name: service
      port: 9000
      protocol: TCP
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blobs-minio
  labels:
    app: minio
    chart: minio-2.5.6
    release: blobs
    heritage: Tiller
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: "Parallel"
  serviceName: blobs-minio-svc
  replicas: 4
  selector:
    matchLabels:
      app: minio
      release: blobs
  template:
    metadata:
      name: blobs-minio
      labels:
        app: minio
        release: blobs
    spec:
      serviceAccountName: "blobs-minio"
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-08-01T22-18-54Z
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh",
          "-ce",
          "/usr/bin/docker-entrypoint.sh minio -C /root/.minio/ server
          http://blobs-minio-0.blobs-minio-svc.ystack.svc.cluster.local/export
          http://blobs-minio-1.blobs-minio-svc.ystack.svc.cluster.local/export
          http://blobs-minio-2.blobs-minio-svc.ystack.svc.cluster.local/export
          http://blobs-minio-3.blobs-minio-svc.ystack.svc.cluster.local/export" ]
          
          volumeMounts:
            - name: export
              mountPath: /export
            
            - name: minio-config-dir
              mountPath: /root/.minio/
          ports:
            - name: service
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: blobs-minio
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blobs-minio
                  key: secretkey
            - name: MINIO_BROWSER
              value: "on"
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: service
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            
      volumes:
        - name: minio-user
          secret:
            secretName: blobs-minio
        - name: minio-config-dir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: export
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

