---
# Source: minio/templates/statefulset.yaml


apiVersion: v1
kind: Service
metadata:
  name: release-name-minio-svc
  labels:
    app: minio
    chart: "minio-2.4.13"
    release: "release-name"
    heritage: "Tiller"
spec:
  clusterIP: None
  ports:
    - name: service
      port: 9000
      protocol: TCP
  selector:
    app: minio
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: release-name-minio
  labels:
    app: minio
    chart: minio-2.4.13
    release: release-name
    heritage: Tiller
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: release-name-minio-svc
  replicas: 4
  selector:
    matchLabels:
      app: minio
      release: release-name
  template:
    metadata:
      name: release-name-minio
      labels:
        app: minio
        release: release-name
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-04-09T01-22-30Z
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh",
          "-ce",
          "/usr/bin/docker-entrypoint.sh minio -C /root/.minio/ server
          http://release-name-minio-0.release-name-minio-svc.default.svc.cluster.local/export
          http://release-name-minio-1.release-name-minio-svc.default.svc.cluster.local/export
          http://release-name-minio-2.release-name-minio-svc.default.svc.cluster.local/export
          http://release-name-minio-3.release-name-minio-svc.default.svc.cluster.local/export" ]
          
          volumeMounts:
            - name: export
              mountPath: /export
            
            - name: minio-config-dir
              mountPath: /root/.minio/
          ports:
            - name: service
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-minio
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-minio
                  key: secretkey
            - name: MINIO_BROWSER
              value: "on"
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: service
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            
      volumes:
        - name: minio-user
          secret:
            secretName: release-name-minio
        - name: minio-config-dir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: export
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

