---
# Source: mimir/templates/ruler/ruler-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mimir-ruler
  labels:
    helm.sh/chart: mimir-4.3.0
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/component: ruler
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: "2.7.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
  namespace: "mimir"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/component: ruler
