---
# Source: mimir/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mimir
  labels:
    helm.sh/chart: mimir-4.3.0
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "2.7.1"
    app.kubernetes.io/managed-by: Helm
  namespace: "mimir"
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [mimir]
