---
# Source: mimir/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir
  labels:
    helm.sh/chart: mimir-3.0.0
    app.kubernetes.io/name: mimir
    #app.kubernetes.io/instance: unhelm
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
  namespace: "mimir"
